# Bandit configuration for python-proptest
# We use random module for property-based testing, not security/crypto

# Skip B311: Standard pseudo-random generators are not suitable for security/cryptographic purposes
# This is a false positive for property-based testing libraries
skips:
  - B311

# Exclude test files from security scanning
exclude_dirs:
  - tests
  - examples

# Set confidence level (High, Medium, Low)
confidence: Medium

# Set severity level (High, Medium, Low)
severity: Medium

