site_name: 'python-proptest'
site_description: 'Python Property-Based Testing Library'
site_author: 'kindone'
site_url: 'https://kindone.github.io/python-proptest'
site_dir: 'site'

repo_name: 'kindone/python-proptest'
repo_url: 'https://github.com/kindone/python-proptest'
edit_uri: 'edit/main/docs'

theme:
  name: material
  font:
    text: 'Inter'
    code: 'Spline Sans Mono'
  palette:
    primary: teal
    accent: light green
  favicon: assets/favicon.ico
  features:
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - toc.follow
    - navigation.top
    - search.highlight
    - search.suggest
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - meta
  - footnotes
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized
  - mermaid2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kindone/python-proptest

nav:
  - 'Introduction': index.md
  - 'Generators': generators.md
  - 'Combinators': combinators.md
  - 'Properties': properties.md
  - 'Decorators': decorators.md
  - 'Shrinking': shrinking.md
  - 'Stateful Testing': stateful-testing.md
  - 'Pytest Integration': pytest-integration.md
  - 'Unittest Integration': unittest-integration.md
  - 'Pytest Best Practices': pytest-best-practices.md
